### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by dcboy** [zhongbiaodev/py-mysql-elasticsearch-sync#9]
pip -vv install py-mysql-elasticsearch-sync
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting py-mysql-elasticsearch-sync
  Getting page http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/
  Starting new HTTP connection (1): mirrors.aliyun.com
  "GET /pypi/simple/py-mysql-elasticsearch-sync/ HTTP/1.1" 200 None
  1 location(s) to search for versions of py-mysql-elasticsearch-sync:
- http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/
  Getting page http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/
  "GET /pypi/simple/py-mysql-elasticsearch-sync/ HTTP/1.1" 200 None
  Analyzing links from page http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/
    Found link http://mirrors.aliyun.com/pypi/packages/2.7/p/py-mysql-elasticsearch-sync/py_mysql_elasticsearch_sync-0.3.0-py2.py3-none-any.whl#md5=4c77aa1fcdcd6d4a570e58d65b6ed0b1 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.3.0
    Found link http://mirrors.aliyun.com/pypi/packages/2.7/p/py-mysql-elasticsearch-sync/py_mysql_elasticsearch_sync-0.3.2-py2.py3-none-any.whl#md5=faf144d93d3f82c8bd087386a2dfea85 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.3.2
    Found link http://mirrors.aliyun.com/pypi/packages/2.7/p/py-mysql-elasticsearch-sync/py_mysql_elasticsearch_sync-0.3.3.1-py2.py3-none-any.whl#md5=0b88f54799e02ec0875b7708ef816455 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.3.3.1
    Found link http://mirrors.aliyun.com/pypi/packages/2.7/p/py-mysql-elasticsearch-sync/py_mysql_elasticsearch_sync-0.3.3.2-py2.py3-none-any.whl#md5=a8b4f98c128a20f427764b33dd35bfb2 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.3.3.2
    Skipping link http://mirrors.aliyun.com/pypi/packages/3.5/p/py-mysql-elasticsearch-sync/py_mysql_elasticsearch_sync-0.2.1-py3-none-any.whl#md5=ebe524a047e5437892f8506e1815e9b3 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/); it is not compatible with this Python
    Found link http://mirrors.aliyun.com/pypi/packages/source/p/py-mysql-elasticsearch-sync/py-mysql-elasticsearch-sync-0.2.1.tar.gz#md5=58d4f4b7905ba6b6a8cd6f25a5dbb1d6 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.2.1
    Found link http://mirrors.aliyun.com/pypi/packages/source/p/py-mysql-elasticsearch-sync/py-mysql-elasticsearch-sync-0.3.0.tar.gz#md5=2ac412df604fdfa7a7904e31636afe5b (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.3.0
    Found link http://mirrors.aliyun.com/pypi/packages/source/p/py-mysql-elasticsearch-sync/py-mysql-elasticsearch-sync-0.3.2.tar.gz#md5=8e0d6126adadad61b5a0618533971a56 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.3.2
    Found link http://mirrors.aliyun.com/pypi/packages/source/p/py-mysql-elasticsearch-sync/py-mysql-elasticsearch-sync-0.3.3.1.tar.gz#md5=91ac5d579ec7c9c56e7a49b310529bde (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.3.3.1
    Found link http://mirrors.aliyun.com/pypi/packages/source/p/py-mysql-elasticsearch-sync/py-mysql-elasticsearch-sync-0.3.3.2.tar.gz#md5=a3e12f3d88167db51e8eed30ef9af485 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.3.3.2
    Found link http://mirrors.aliyun.com/pypi/packages/source/p/py-mysql-elasticsearch-sync/py-mysql-elasticsearch-sync-0.3.4.1.tar.gz#md5=3c3d78a4d5f1826114031ec5deab74b7 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/), version: 0.3.4.1
  Using version 0.3.4.1 (newest of versions: 0.3.4.1, 0.3.3.2, 0.3.3.2, 0.3.3.1, 0.3.3.1, 0.3.2, 0.3.2, 0.3.0, 0.3.0, 0.2.1)
  "GET /pypi/packages/source/p/py-mysql-elasticsearch-sync/py-mysql-elasticsearch-sync-0.3.4.1.tar.gz HTTP/1.1" 200 11443
  Downloading http://mirrors.aliyun.com/pypi/packages/source/p/py-mysql-elasticsearch-sync/py-mysql-elasticsearch-sync-0.3.4.1.tar.gz
  Downloading from URL http://mirrors.aliyun.com/pypi/packages/source/p/py-mysql-elasticsearch-sync/py-mysql-elasticsearch-sync-0.3.4.1.tar.gz#md5=3c3d78a4d5f1826114031ec5deab74b7 (from http://mirrors.aliyun.com/pypi/simple/py-mysql-elasticsearch-sync/)
  Running setup.py (path:/tmp/pip-build-0mVEJh/py-mysql-elasticsearch-sync/setup.py) egg_info for package py-mysql-elasticsearch-sync
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-0mVEJh/py-mysql-elasticsearch-sync/setup.py", line 2, in <module>
        import es_sync
      File "es_sync/**init**.py", line 2, in <module>
        from future.builtins import str, range
    ImportError: No module named future.builtins
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-0mVEJh/py-mysql-elasticsearch-sync/setup.py", line 2, in <module>
        import es_sync
      File "es_sync/**init**.py", line 2, in <module>
        from future.builtins import str, range
    ImportError: No module named future.builtins
  ---
  
  Cleaning up...
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0mVEJh/py-mysql-elasticsearch-sync
  Exception information:
  Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/usr/lib/python2.6/site-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.6/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/usr/lib/python2.6/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/usr/lib/python2.6/site-packages/pip/req/req_set.py", line 505, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.6/site-packages/pip/req/req_set.py", line 123, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.6/site-packages/pip/req/req_install.py", line 407, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.6/site-packages/pip/utils/__init__.py", line 732, in call_subprocess
    % (command_desc, proc.returncode, cwd))
  InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0mVEJh/py-mysql-elasticsearch-sync

**Comment by zjutsuper** [comment]
I have also the same problem with you !!

Collecting py-mysql-elasticsearch-sync
  Using cached py-mysql-elasticsearch-sync-0.3.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-iGRbYP/py-mysql-elasticsearch-sync/setup.py", line 2, in <module>
        import es_sync
      File "/tmp/pip-build-iGRbYP/py-mysql-elasticsearch-sync/es_sync/**init**.py", line 2, in <module>
        from future.builtins import str, range
    ImportError: No module named future.builtins

**Comment by huangweicong112** [comment]
sorry for late reply.

Can you check where the package future is installed or not? It should be required.

**Comment by dcboy** [comment]
hi :
what’s your python version,try to upgrade 3.x i have been solve that

原始邮件
发件人:zjutsupernotifications@github.com
收件人:zhongbiaodev/py-mysql-elasticsearch-syncpy-mysql-elasticsearch-sync@noreply.github.com
抄送:dcboyszdcboy@gmail.com; Authorauthor@noreply.github.com
发送时间:2016年7月12日(周二) 20:10
主题:Re: [zhongbiaodev/py-mysql-elasticsearch-sync] can't install (#9)

I have also the same problem with you !!
Collecting py-mysql-elasticsearch-sync
 Using cached py-mysql-elasticsearch-sync-0.3.4.1.tar.gz
 Complete output from command python setup.py egg_info:
 Traceback (most recent call last):
 File "", line 1, in 
 File "/tmp/pip-build-iGRbYP/py-mysql-elasticsearch-sync/setup.py", line 2, in 
 import es_sync
 File "/tmp/pip-build-iGRbYP/py-mysql-elasticsearch-sync/es_sync/init.py", line 2, in 
 from future.builtins import str, range
 ImportError: No module named future.builtins
